services:
  postgres:
    image: ${PG_APP}
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGA_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGA_PASS}
    ports:
      - 5050:80

volumes:
  db-volume:
