services:
  postgres:
    image: ${PG_APP}
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./db-volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGA_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGA_PASS}
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=${PG_NAME}
      - MYSQL_USER=${MY_USER}
      - MYSQL_ROOT_PASSWORD=${MY_PASS}
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${PGA_PASS}
      - PMA_HOST=mysql
    ports:
      - 8080:80
